defaults: &defaults
  app_name: 'RailsBootstrap'
  nested_config:
    first_level: 'first level value'
    array_config:
      - 'one'
      - 'two'

development:
  <<: *defaults
  sample: "development"

test:
  <<: *defaults
  sample: "test"

production:
  <<: *defaults
  sample: "production"
